version: "3.8"

services:

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: MappingDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - db
    ports:
      - "8761:8765"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/MappingDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

volumes:
  postgres_data: